package org.jahia.utils.maven.plugin.osgi;

import org.apache.commons.io.IOUtils;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.project.MavenProject;
import org.jahia.utils.osgi.BundleUtils;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.jar.JarInputStream;

/**
 * A new goal to provide tools to inspect OSGi bundles, either generated by the project or specified as a
 * parameter.
 *
 * @goal osgi-inspect
 */
public class OsgiInspectorMojo extends AbstractMojo {

    /**
     * @parameter default-value="${jarBundles}"
     */
    protected List<String> jarBundles = new ArrayList<String>();

    /**
     * @parameter expression="${project}"
     * @readonly
     * @required
     */
    protected MavenProject project;

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        if (jarBundles == null || jarBundles.size() == 0) {
            jarBundles = new ArrayList<String>();
            String extension = project.getPackaging();
            if ("bundle".equals(extension)) {
                extension = "jar";
            }
            jarBundles.add(project.getBuild().getDirectory() + "/" + project.getBuild().getFinalName() + "." + extension);
        }
        for (String jarBundle : jarBundles) {
            JarInputStream jarInputStream = null;
            try {
                jarInputStream = new JarInputStream(new FileInputStream(jarBundle));
                StringWriter stringWriter = new StringWriter();
                PrintWriter stringPrintWriter = new PrintWriter(stringWriter);
                BundleUtils.dumpManifestHeaders(jarInputStream, stringPrintWriter);
                getLog().info(jarBundle + " header dump:\n" + stringWriter.getBuffer().toString());
            } catch (IOException e) {
                e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
            } finally {
                IOUtils.closeQuietly(jarInputStream);
            }
        }
    }
}
