# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On merge to master

# The workflow could also be triggered on PRs
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  publish:
    name: Build Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: mvn --settings .github/maven.settings.xml --batch-mode --update-snapshots  deploy
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jahia-configuration
          path: ./**/target/*
          retention-days: 2
